import PS5 from "./assets/ps5.jpg"
import wristWatch from "./assets/wristwatch.png"
import blackBuds from "./assets/budsOnSale.jpg"
import mouse from "./assets/mouse.jpg"
import whiteBuds from "./assets/whiteBudsOnSale.jpg"
import powerBank from "./assets/powerBank.jpg"
import Iphone15 from "./assets/Iphone15 proMax.jpg"
import SecondIphone15img from "./assets/secondIphone15img.jpg"
import ThirdIphone15img from "./assets/thirdIphone15Img.jpg"
import FourthIphone15img from "./assets/fourthIphone15img.png"
import AppleWatch from "./assets/AppleWatchUltra.jpg"
import MacBook from "./assets/MacBookPro.jpg"
import GoogleNextHubMax from "./assets/GoogleNextHubMax.jpg"
import SonyWH from "./assets/SonyWH.jpg"
import AirpodsPro2ndGen from "./assets/AirpodsPro2ndGen.jpg"
import DellLaptop from "./assets/laptopdell.png"
import IphoneCase from "./assets/iphonecase.png"

export const products = [
  {
    id: 1,
    image: Iphone15,
    imageGallery: [Iphone15, SecondIphone15img, ThirdIphone15img, Iphone15],
    brand: "Apple",
    writeUp:
      "iPhone 15 Pro Max. Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever",
    name: "Iphone 15 Pro max",
    description: "256GB • Titanium Gray",
    rating: 4.6,
    reviews: 15,
    price: 1200000,
    oldPrice: null,
    displayPrice: "₦1,200,000",
    displayOldPrice: null,
    isNew: true,
    isTrending: true,
    category: "Smartphones",
    isOnSale: false,
    isInStock: true,
    color: "Titanium Gray",
    colorOptions: [
    {name: "Blue",
     colorCode : "#9EC0FF"
    },
    {name: "Titanium Gray",
     colorCode : "#D6D7D8"
    },
    {name: "Black",
     colorCode:"#191C1F"
    },
    {name:"White",
     colorCode:"#FBFDFF",
    }],
    storage: "256GB",
    storageOptions: ["128GB", "256GB", "512GB", "1TB"],
    specifications: {
    Display: "6.7″ Super Retina XDR OLED",
    Processor: "A17 Pro Chip",
    RAM: "8GB",
    Storage: "256GB",
    "Main Camera": "48MP + 12MP + 12MP",
    "Front Camera": "12MP TrueDepth",
    Battery: "4422 mAh",
    Charging: "USB-C, MagSafe, Qi",
    OS: "iOS 17",
    Dimensions: "159.9 × 76.7 × 8.25 mm",
    Weight: "220g",
    "Water Resistance": "IP68",
  },

  },
  {
    id: 2,
    image: PS5,
    imageGallery : [PS5],
    brand: "Sony",
    writeUp: "Next-gen console delivering lightning-fast load times and immersive gameplay.",
    name: "Play Station 5",
    description: "Digital Edition • 1TB",
    rating: 4.6,
    reviews: 15,
    price: 1200000,
    oldPrice : null,
    displayPrice: "₦1,200,000",
    displayOldPrice: null,
    isNew: true,
    isTrending: true,
    category: "Gaming",
    isOnSale: false,
    isInStock: true,
    color: "White",
    colorOptions: [],
    storage: "1TB",
    storageOptions: ["825GB", "1TB"],
    specifications: {
      Processor: "AMD Ryzen Zen 2",
      GPU: "RDNA 2",
    },
  },
  {
    id: 3,
    image: AppleWatch,
    imageGallery: [AppleWatch],
    brand : "Apple",
    writeUp: "Built for endurance, exploration, and advanced health tracking.",
    name: "Apple Watch Ultra 2",
    description: "Titanium • GPS + Cellular",
    rating: 4.6,
    reviews: 15,
    price: 1200000,
    oldPrice : null,
    displayPrice: "₦1,200,000",
    displayOldPrice: null,
    isNew: true,
    isTrending: true,
    category: "Wearables",
    isOnSale: false,
    isInStock: true,
    color: "Titanium",
    colorOptions: [],
    storage: null,
    storageOptions: [],
    specifications: {
      Display: "49mm Retina",
      Battery: "36 hours",
    },
  },
  {
    id: 4,
    image: MacBook,
    imageGallery: [MacBook],
    brand: "Apple",
    writeUp: "Extreme performance with Apple’s most powerful silicon yet.",
    name: "Macbook Pro 16",
    description: "M3 Max • 32GB RAM",
    rating: 4.6,
    reviews: 15,
    price: 1200000,
    oldPrice: null,
    displayPrice: "₦1,200,000",
    displayOldPrice: null,
    isNew: true,
    isTrending: true,
    category: "Laptops",
    isOnSale: false,
    isInStock: true,
    color: "Space Gray",
    colorOptions: [],
    storage: "1TB",
    storageOptions: ["512GB", "1TB", "2TB"],
    specifications: {
      Processor: "Apple M3 Max",
      RAM: "32GB",
    },
  },
  {
    id: 5,
    image: wristWatch,
    imageGallery: [wristWatch],
    brand: "Samsung",
    writeUp: "Classic design with powerful health and fitness tracking.",
    name: "Samsung Galaxy Watch 6 Classic",
    description: "47mm, Rotating Bezel",
    rating: 4.6,
    reviews: 15,
    price: 1200000,
    oldPrice : null,
    displayPrice : "₦1,200,000",
    displayOldPrice : null,
    isNew: false,
    isTrending: true,
    category: "Wearables",
    isOnSale: false,
    isInStock: true,
    color: "Black",
    colorOptions: [],
    storage: null,
    storageOptions: [],
    specifications: {},
  },
  {
    id: 6,
    image: GoogleNextHubMax,
    imageGallery: [GoogleNextHubMax],
    brand: "Google",
    writeUp: "Smart display designed to control your entire home.",
    name: "Google Next Hub Max",
    description: '"10" Display, Smart Home Hub',
    rating: 4.6,
    reviews: 15,
    price: 1200000,
    oldPrice : null,
    displayPrice: "₦1,200,000",
    displayOldPrice : null,
    isNew: false,
    isTrending: true,
    category: "Smart Homes",
    isOnSale: false,
    isInStock: true,
    color: "White",
    colorOptions: [],
    storage: null,
    storageOptions: [],
    specifications: {},
  },
  {
    id: 7,
    image: SonyWH,
    imageGallery: [SonyWH],
    brand: "Sony",
    writeUp: "Industry-leading noise cancellation with premium sound.",
    name: "Sony WH - 1000345",
    description: "Noise Cancelling, 30h Battery",
    rating: 4.6,
    reviews: 15,
    price: 1200000,
    oldPrice: null,
    displayPrice: "₦1,200,000",
    displayOldPrice: null,
    isNew: true,
    isTrending: true,
    category: "Accessories",
    isOnSale: false,
    isInStock: true,
    color: "Black",
    colorOptions: [],
    storage: null,
    storageOptions: [],
    specifications: {},
  },
  {
    id: 8,
    image: AirpodsPro2ndGen,
    imageGallery: [AirpodsPro2ndGen],
    brand: "Apple",
    writeUp: "Adaptive audio with next-level active noise cancellation.",
    name: "Airpods Pro 2nd Gen",
    description: "USB-C, Adaptive Audio",
    rating: 4.6,
    reviews: 15,
    price: 1200000,
    oldPrice: null,
    displayPrice: "₦1,200,000",
    displayOldPrice: null,
    isNew: true,
    isTrending: true,
    category: "Accessories",
    isOnSale: false,
    isInStock: true,
    color: "White",
    colorOptions: [],
    storage: null,
    storageOptions: [],
    specifications: {},
  },
  {
    id: 9,
    image: DellLaptop,
    imageGallery: [DellLaptop],
    brand: "Dell",
    writeUp: "Reliable performance laptop for work and productivity.",
    name: "Dell Laptop",
    description: "M3 Max • 32GB RAM",
    rating: 4.6,
    reviews: 15,
    price: 1200000,
    oldPrice : null,
    displayPrice: "₦1,200,000",
    displayOldPrice: null,
    isNew: true,
    isTrending: false,
    category: "Laptops",
    isOnSale: false,
    isInStock: true,
    color: "Gray",
    colorOptions: [],
    storage: "512GB",
    storageOptions: [],
    specifications: {},
  },
  {
    id: 10,
    image: IphoneCase,
    name: "Iphone case",
    description: "",
    rating: 0,
    reviews: 0,
    price: 1200000,
    displayPrice: "₦1,200,000",
    isNew: true,
    isTrending: false,
    category: "Accessories",
    isOnSale: false,
  },
  {
    id: 11,
    name: "Oriamo FlipBuds Pro",
    description: "",
    rating: 0,
    reviews: 0,
    price: 1200000,
    displayPrice: "₦1,200,000",
    isNew: true,
    isTrending: false,
    category: "Accessories",
    isOnSale: false,
  },
  {
    id: 12,
    name: "Samsung Galaxy Buds 2 Pro",
    description: "Black",
    image: blackBuds,
    rating: 0,
    reviews: 0,
    price: 1200000,
    displayPrice: "₦1,200,000",
    oldPrice: 100000,
    displayOldPrice: "₦100,000",
    isNew: false,
    isTrending: false,
    category: "Accessories",
    isOnSale: true,
  },
  {
    id: 13,
    name: "Samsung Galaxy Buds 2 Pro",
    description: "USB-C, Adaptive Audio",
    image: whiteBuds,
    rating: 0,
    reviews: 0,
    price: 1200000,
    displayPrice: "₦1,200,000",
    oldPrice: 100000,
    displayOldPrice: "₦100,000",
    isNew: false,
    isTrending: false,
    category: "Accessories",
    isOnSale: true,
  },
  {
    id: 14,
    name: "Wireless Mouse",
    image: mouse,
    description: "USB-C, with lights",
    rating: 0,
    reviews: 0,
    price: 1200000,
    displayPrice: "₦1,200,000",
    oldPrice: 100000,
    displayOldPrice: "₦100,000",
    isNew: false,
    isTrending: false,
    category: "Accessories",
    isOnSale: true,
  },
  {
    id: 15,
    name: "Power Bank",
    image: powerBank,
    description: "Lasts 24hrs",
    rating: 0,
    reviews: 0,
    price: 1200000,
    displayPrice: "₦1,200,000",
    oldPrice: 100000,
    displayOldPrice: "₦100,000",
    isNew: false,
    isTrending: false,
    category: "Accessories",
    isOnSale: true,
  },
];